apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-app-secret
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: example-app-secret
  data:
    - secretKey: api-key
      remoteRef:
        key: demo/example-app/api-key
